### ISSUE TITLE
remove some bundle output

### ISSUE THREAD

**Issue by aladdin-add** [cherow/cherow#299] opened 2019-01-18 16:36 UTC
bundled output on my local computer:
![image](https://user-images.githubusercontent.com/13050025/51399368-bf414380-1b80-11e9-834e-90e6919e419a.png)

+ too many output files ( 6*2=12  `['amd' | 'cjs' | 'system' | 'es' | 'esm' | 'iife' | 'umd'] * ['normal', 'minified']`), but only one is needed for most users.
+ seems https://github.com/cherow/cherow/issues/255 still happened.

**Comment by fkleuver** [comment] 2019-01-18 16:58
Too many for what?
Which ones do you propose removing?

**Comment by aladdin-add** [comment] 2019-01-18 17:15
https://github.com/cherow/cherow/blob/7e9864413c9d46e1a1280e991e7dd8b1fbdb6ed2/package.json#L5-L8

I'm seeing `umd` and `esm` were in the `package.json`, others seems unnecessary to me. (just my 2c :(

**Comment by fkleuver** [comment] 2019-01-18 18:38
The ones specified in the package.json are just targeted at the majority of bundlers that use these standards. It's not a limiting factor in what you *can* use.

### IIFE
 `iife` allows you to include the package with an inline script tag, without the need for any bundler.
Look, a very simple REPL that consists of 1 html page, 2 html elements and 4 lines of javascript code: https://gist.run/?id=93303932473a0374ca69cceafb80092c

All you need is `<script src="path-to-iife.js"></script>`, write `cherow.parse` and off you go.
Of course an html page does not need to look at the package.json.

### SystemJS
This is for the `jspm` / `systemjs` combo which is an older loader created by the same author that created rollup. It is its own module format and having a special bundle output for that is the only way to serve those folks. They can simply specify the path to `node_modules/cherow/dist/cherow.system.js` directly in their config.js

### AMD / CJS
UMD combines these two (as well as iife) but also adds bloat, and may even cause issues in some rare scenarios. If you want to use for example `require.js`, you only need the AMD portion and thus directly referencing the AMD bundle gives you the most efficient result. Similar to iife and systemjs, it is common in this loader to specify the path directly instead of auto-resolving based on package.json. Same goes for CJS in some old setups.

### Conclusion
I have spent hundreds of hours on dozens of different bundlers, loaders, plugins and nonsense over the last few years and accumulated enough experience to know that these outputs, even if the majority don't need them, are valuable to some. And those who don't need it, don't care.

It can on the other hand be infuriating when an important library only bothers to serve `umd` or `esm` and you are in that one pesky situation where your existing app/environment doesn't work with that. The majority of publishers do it poorly like that, and cherow should not be one of those. 

It's not like npm is running short on space or 500kb extra on a user's local hard drive during development matters between the existing 200mb, does it?

### Going forward
Instead of cleaning up, there are going to be *more* outputs. Someone reported an issue related to ES5 the other day caused by his babel settings being wrong. Why wouldn't we flip a switch and provide 24 outputs instead of 12, with each variant in ES5 as well? No effort or burden for us, potentially many hours saved for users that need to run cherow in IE11.

Time to think differently about this @cherow/cherow-team , the goal is not to make the dist folder look pretty, the goal is that it works for everyone as simply as possible,

**Closed by fkleuver** 2019-01-18 18:38 UTC
Labels: build
