### ISSUE TITLE
[help wanted] Create a plugin to produce a babel-compatible AST

### ISSUE THREAD

**Issue by rattrayalex** [cherow/cherow#6] opened 2017-09-26 04:30 UTC
Babel is a widely-used tool for transforming JavaScript AST's. 

Its AST structure differs subtly (and, usually, conveniently) from ESTree's. 

An option to output a Babel AST instead of an ESTree may be useful for replacing babylon the babylon parser with something more performant. 

Many people use Babel as a core part of their workflow, so this could help adoption of `cherow` significantly.

EDIT: Seeking help to do this. 

We essentially need to build the inverse of [babylon](https://github.com/babel/babel/tree/master/packages/babylon#output)'s [estree mode](https://github.com/babel/babel/blob/master/packages/babylon/src/plugins/estree.js) or [babel-to-estree](https://github.com/lightscript/babel-to-estree) (derived from eslint's babel support).

**Comment by KFlash** [comment] 2017-09-26 04:47
Isn't the Babel AST only used internal in Babel? Never seen it used as stand-alone. Anyway. ESTree was used as default AST because it's more or less a de-facto standard and widely adopted by everyone even if it has some flaws like the literal node being overloaded. But changing to another AST format that isn't widely adopted isn't on my TODO now. Maybe in the future it can be adopted ss an option. So the optiins can be used to change AST during parsing.

**Comment by KFlash** [comment] 2017-09-26 05:13
Closing this for now. Will re-open if this becomes applicable

**Comment by KFlash** [comment] 2017-09-26 16:23
I have to think about this one. To implement this as an option would require duplicating of the code. Maintaining it isn't the issue. The issue is the size of the code base .

**Comment by rattrayalex** [comment] 2017-09-27 07:43
Ah, interesting. There are only a handful of deviations (mostly literals) so I'm not sure how bad it'd be. Certainly no rush in any case.

**Comment by rattrayalex** [comment] 2017-12-25 13:44
@KFlash curious for your current thoughts here. 

It looks like a `cherow-plugin-babel-ast` seems fairly doable reading your docs on https://github.com/cherow/cherow#plugins. 

`babel-plugin-cherow-parser` could then be built to wrap the two together and set the babel parser (which babel has an option of doing). This might dramatically increase parse times for a large number of people, as babel is both very popular and very slow (from what I am told). 

I will be AFK for 10 days, or I might try to help.

**Comment by KFlash** [comment] 2017-12-25 14:19
Hi. It should be a easy thing to fix I guess, and you may look at this repo for live demo of a working plugin:  https://github.com/cherow/cherow-dummy-plugin.  

I kind of lack some knowledge when it comes to Babels internals, but it seems logic. And by principle I normally let the benchmarks speak for itself when it comes to performance. But it make sense.
It's holly day season around me now, so I'm not online the next days myself either so if you want to create this plugin - feel free to do it.

**Comment by rattrayalex** [comment] 2017-12-25 16:34
Cool! Would you mind reopening this issue in case others are inspired to help? I'll rename it to clarify that it's for making a plugin. 

I don't think I'll have time to make the plugin myself but I'll see if others might be willing to help. 

Happy holidays!

**Comment by KFlash** [comment] 2018-01-09 05:11
@rattrayalex What's your plans / thoughts / ideas regarding this issue per now?

**Comment by rattrayalex** [comment] 2018-01-09 15:53
Thinking about it a little more, I don't think I personally will work on this till it's used in Prettier, which I help maintain. 

That'll be a terrific use-case, I think, and help prove out the stability of Cherow prior to using it as a compiler.

**Comment by rattrayalex** [comment] 2018-01-09 16:06
Actually, I don't think I'll personally do any work towards Cherow's use in prettier or babel until Flow is supported (https://github.com/cherow/cherow/issues/35). 

We use Flow at work, and Prettier needs to support Flow, so I can't really justify spending time on this until it's supported.

**Comment by rattrayalex** [comment] 2018-01-09 16:11
I did open a tracking issue on the prettier repo regardless: https://github.com/prettier/prettier/issues/3688 (note that I don't believe they need babel AST output, though it might help)

**Comment by KFlash** [comment] 2018-01-09 16:42
Kind of interesting... I'm in the middle of a finale 1.0 version this days and regarding Flow and TypeScript both has to be a plugin. I'm exposing pre-defined tokens needed for both. So this are in the making.

Regarding Babel AST and Babel in general. This will be easier to handle in the upcoming version wich will be the finale version. 

I let this issue stay open and will open another issue later with the upcoming changes. E.g. tokenization, walker, editor mode etc.

**Comment by rattrayalex** [comment] 2018-01-09 16:45
Awesome, sounds great! Good luck!

**Comment by KFlash** [comment] 2018-01-10 04:47
@rattrayalex You can see [this](https://github.com/cherow/cherow/issues/68) for info about 1.0 version. Flow and TypeScript will be added now as part of the internal API system. Very much how Babylon does it, but with improved performance.

**Here is how the Flow plugin looks like just now**

```js
export function FlowParser(Cherow: any): any {
    return class Flow extends Cherow {
         constructor(source: string, opts: Options) {
             super(source, opts);
         }
    };
}
```

**Comment by KFlash** [comment] 2018-01-10 07:10
@rattrayalex I'm working on Flow implementation now. Does it exist any ESTree look-a-like specs for the AST nodes? 

For now it's only possible to parse `var foo: number`, but the interal plugin system now works!

You can see the plugin [here](https://github.com/cherow/cherow/blob/1.0/plugins/flow/parser.ts),

**Comment by rattrayalex** [comment] 2018-01-10 16:30
Nice! Lots of progress today! Impressive. 

Let's move Flow conversation over to #35

**Comment by KFlash** [comment] 2018-01-17 10:04
I'm closing this. I put it on my own TODO and the plugin will be located [here](https://github.com/cherow/cherow-babylon-ast-plugin) in the future.

**Closed by KFlash** 2018-01-17 10:04 UTC
Labels: help wanted

**Comment by hzoo** [comment] 2018-01-29 18:52
Probably a lot of work someone will have to take on - but if it's finished and can be maintained/extended we could also consider just moving to cherow for the babel parser (it's switchable anyway) if there is an AST compat (need to add in the same parser options, error messages maybe, and then the stage-x plugins)

**Comment by KFlash** [comment] 2018-01-29 22:34
@hzoo Creating a Babel AST plugin isn't very difficult, but yeah time consuming. It's on my TODO list.
If you look at the [1.0 branch](https://github.com/cherow/cherow/tree/1.0) you can see the future of Cherow. I rewrote it to be faster, smaller and to support seceral options so it can be extended with plugins. That branch is almost done now except for the non-failing Test262 tests. I'm working on that now. 
It will be as flexible as Babylon itself, and easy enough to write plugins. It already exists a [cherow-do-expressions plugin (stage 1)](https://github.com/cherow/cherow-do-expressions). Something I wrote just to check if the plugin system works as it should.
Flow are supported as well, but that plugin need to be refactored a little before I push it again. 
I also started to work on a TypeScript plugin, but will finish it soon after 1.0. have been completed.
If you look [here](https://github.com/cherow) you can see the list for plugins I'm going to add to Cherow soon. Both Stage 1 and Stage 2 are on that list as well.
Why I created Cherow? The main reason is that I prefer code that is super fast, use less memory and just do what it should do. Plus that more and more JS tools require parsing support, and slower parsers result in slower tools. 
And existing parsers have too many issues with them. E.g. Acorn is slow and it often is too permissive in what it accepts. It's also a bit bloated. Esprima is faster than Acorn, but it misses a lot of edge cases. 
If you sum it up it's fair enough to claim that none of these parsers would fare any chance against the official Test262 suite, and most fail a substantial number of them. 
So it was easier just to write something from scratch.

**Comment by KFlash** [comment] 2018-01-30 04:36
@hzoo My basic idea for different AST's is to use an object to return correct AST format to the caller. This can be changed through plugins. Using an Class for this isn't an option due to performance reasons.  But not sure yet how this could be done without huge impact on code size as well.

```js
const AST = {
   assignmentExpression: (value1, value2) {}
}

return AST.assignmentExpression(1, 2);
```

**Comment by rattrayalex** [comment] 2018-01-30 15:03
Excited to see you here, @hzoo !
